[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
dotenv = "0.15"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
utils = {path = "utils" }
tokio = { version = "1", features = ["full"] }

[dev-dependencies]
axum-macros = "0.4.1"

[workspace]
members = ["utils"]
