[package]
name = "pizzeria"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
dotenv = "0.15"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
sqlx = { version = "0.8.3", features = ["runtime-tokio", "postgres"] }
utils = {path = "crates/utils" }
tokio = { version = "1.43", features = ["full"] }
tower-http = { version = "0.6.2", features = ["cors"] }

[dev-dependencies]
axum-macros = "0.4.1"

[profile.release]
opt-level = 3
lto = "fat"
debug = false
strip = true
panic = "abort"
