[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
dotenv = "0.15"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sqlx = { version = "0.7", features = ["runtime-tokio", "postgres"] }
utils = {path = "utils" }
tokio = { version = "1", features = ["full"] }
tower_governor = "0.3.2"
tower-http = { version = "0.5.2", features = ["cors"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
axum-macros = "0.4.1"
reqwest = "0.12.3"
tokio = { version = "1", features = ["full"] }

[profile.release]
strip = true
lto = true
panic = 'abort'
