services:
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:17-alpine
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/20240321181200_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env

volumes:
  db-data: