version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./migrations/20240321181200_init.up.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:

#    healthcheck:
#      test: [ "CMD", "pg_isready" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5