[package]
name = "jwt"
version = "0.1.0"
edition.workspace = true

[dependencies]
axum.workspace = true
axum-extra.workspace = true
api-response.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
jsonwebtoken.workspace = true
chrono.workspace = true
